#:schema https://mise.jdx.dev/schema/mise.json

[plugins]
	butane = "https://github.com/Okeanos/asdf-butane"
	taplo = "https://github.com/Okeanos/asdf-taplo"

# See https://github.com/jdx/mise/blob/main/registry.toml for what is officially available
# Everything else is just declared as a reference to keep track of it.
[tools]
	butane = "0.22.0"
	editorconfig-checker = "3.0.3"
	gitleaks = "8.18.4"
	markdownlint-cli2 = "0.13.0"
	shellcheck = "0.10.0"
	shfmt = "3.9.0"
	taplo = "0.9.3"
	yamllint = "1.35.1"
